### PR TITLE
feat(policies): allow policy to accept arguments from the configuration file

### PR DESCRIPTION
**Pull request by timothyrchew**

### CODE REVIEW

**Comment by Ignigena** [comment]
@timothyrchew This is great, and I love the flexibility it will give us without a lot of added code!

Want to get your thoughts on the choice of enforcing `policy.args` as an Array?

If we're only providing a single argument, in the case of a String, it seems a bit overkill to require the policy to traverse the array to pull out the argument necessary. It makes the code a bit less readable too. I noticed this particularly when reading the test policy.

It seems the biggest benefit from enforcing an array would be the ability to curry the policy function and support multiple named parameters. Using your test as an example:

```
'/knock': {
  fn(req, res, next) {
    return function(fruit) {
      if (fruit === 'orange') return res.ok();
      res.forbidden();
    };
  },
  args: 'orange',
},
```

The benefit of this approach is we're leaving it up to the implementation to decide how arguments are used. I can pass multiple parameters as separate arguments if I like or lump everything up in a single object. The downside is it is a bit more verbose as far as the writing of the policy goes (although this could be a benefit too)

If the function currying doesn't sit well, I'd say just preserve the type provided to `policy.args` rather than wrapping it. This will keep it flexible and allow for simple functions to just pass a string or more advanced requirements to use an object based on preference.

Thoughts?

**Comment by timothyrchew** [comment]
Ah yes this makes a lot more sense. I think I somehow got started with the false assumption that the arguments needed to be strings or arrays of strings, like we currently use. But there is no reason that has to be the case and its totally unnecessary. Will update the argument param to take a single flexible value.

**Comment by timothyrchew** [comment]
Updated

**Comment by Ignigena** [comment]
Merged in  48f46dd  👍

**Pull request closed without merging**
